Feature Omniauth GitHub
CheatCheet/cheatcheet pull request #17
Opened 2021-12-04 00:56 UTC by phanremy

2021-12-04 00:57 UTC, phanremy commented
To Decide: J'ai mis des commentaires pour les méthodes a activer si github est la seule option pour login,
A décider également si cette feature est nécéssaire dans l'immédiat (notamment pour les tests"

2021-12-04 09:43 UTC, b0rdjack commented
> To Decide: J'ai mis des commentaires pour les méthodes a activer si github est la seule option pour login, A décider également si cette feature est nécéssaire dans l'immédiat (notamment pour les tests"

À mon avis, on devrait le mettre par défaut, mais laisser le système de login avec e-mail et mot de passe. Étant donné que lorsqu'un utilisateur se connect avec Github, il ne peut pas de toute manière se connecter avec son e-mail et mot de passe directement sur CheatCheet.

2021-12-04 09:45 UTC, b0rdjack commented
Mais pour le coup il nous manque des tests, je pourrai les implémenter en m'inspirant de ce modèle: https://gist.github.com/mhenrixon/af20677b1cc5670712ccd13d88e5a9f5

2021-12-04 12:22 UTC, b0rdjack requested changes

2021-12-04 12:22 UTC, b0rdjack commented on Gemfile.lock
> +  omniauth-rails_csrf_protection
Je pense comprends pourquoi on fait ça, mais ça ne serait plus simple de gérer ça avec des callbacks plutôt qu'avec une gem ? 

Comme c'est indiqué ici: https://github.com/omniauth/omniauth/wiki/FAQ#rails-session-is-clobbered-after-callback-on-developer-strategy

2021-12-04 12:22 UTC, b0rdjack commented on config/initializers/devise.rb
> +                  Rails.application.credentials.github[:app_secret],
Pas de clé pour l'environnement du coup ?

2021-12-04 12:29 UTC, phanremy commented on config/initializers/devise.rb
> +                  Rails.application.credentials.github[:app_secret],
peut etre overkill pour les environnements, vu qu’on a pas beaucoup de clés pour l’instant?

2021-12-04 12:31 UTC, b0rdjack commented on config/initializers/devise.rb
> +                  Rails.application.credentials.github[:app_secret],
Oui pas faux 😄

2021-12-04 22:21 UTC, phanremy commented on Gemfile.lock
> +  omniauth-rails_csrf_protection
rails_csrf_protection => à mon avis, il faut garder l'authentification csrf qui est une securité, après je peux me tromper

2021-12-06 10:02 UTC, b0rdjack requested changes

2021-12-06 10:02 UTC, b0rdjack commented on test/controllers/devise/ominiauth_controller.rb
> +    assert_new_user_info(@github_omniauth, User.last)
On pourrait encapsuler l'ensemble des tests dans un `assert_difference` qui prendre en paramètre le `User.count` et dedans tu peux faire tes autres assertions. Qu'en pense-tu ?
https://apidock.com/rails/v5.2.3/ActiveSupport/Testing/Assertions/assert_difference

2021-12-07 11:36 UTC, b0rdjack requested changes

2021-12-07 11:36 UTC, b0rdjack commented on test/controllers/devise/ominiauth_controller.rb
> +    assert_new_user_info(@github_omniauth, User.last)
Est-ce qu'on pourrait aussi mettre ces deux asserts dans la boucle du `assert_difference` ? Ou peut-être plutôt que de mettre `do...end`, utiliser des `{}` si le assert ne contient qu'une seul condition ?

2021-12-07 11:36 UTC, b0rdjack commented on test/fixtures/users.yml
> +  updated_at: '2021-12-03 09:35:39.831902000 +0000'
👍

2021-12-07 13:38 UTC, phanremy commented on test/controllers/devise/ominiauth_controller.rb
> +    assert_new_user_info(@github_omniauth, User.last)
fait!

2021-12-10 16:27 UTC, b0rdjack approved these changes

2021-12-10 16:43 UTC, merged