Feature tags edit #36
CheatCheet/cheatcheet pull request #41
Opened 2021-12-07 22:54 UTC by phanremy

fix #36

2021-12-09 00:42 UTC, b0rdjack requested changes

2021-12-09 00:42 UTC, b0rdjack commented on app/javascript/controllers/slim_select_controller.js
> +// Run that command whenever you add a new controller
C'est auto-généré ce commentaire ? Car il est déjà présent dans `app/javascript/controllers/index.js`

2021-12-09 00:42 UTC, b0rdjack commented on app/javascript/controllers/slim_select_controller.js
> +    console.log('slim select start')
`console.log` à enlever

2021-12-09 00:42 UTC, b0rdjack commented on app/javascript/controllers/slim_select_controller.js
> +  static targets = []
`targets` inutile du coup ?

2021-12-09 00:42 UTC, b0rdjack commented on app/views/posts/_post.html.erb
> +  </nav>
Il faudrait les afficher autrement, si on met des _anchor_ alors il faut que ça soit un vrai lien imo.

2021-12-09 00:42 UTC, b0rdjack commented on app/controllers/posts_controller.rb
> +    params[:post][:tag_list]
Pourquoi ne pas ajouter `:tag_list` dans `post_params` ? On peut ensuite faire un `@post.update(post_params)` plutôt que le `assign_attributes`.

2021-12-09 03:11 UTC, phanremy commented on app/views/posts/_post.html.erb
> +  </nav>
en preparation aux index avec recherches eg. `/posts?search=javascript`

2021-12-09 03:11 UTC, phanremy commented on app/controllers/posts_controller.rb
> +    params[:post][:tag_list]
ca n'avais pas l'air de marcher

2021-12-11 19:29 UTC, phanremy commented on app/controllers/posts_controller.rb
> +    params[:post][:tag_list]
params.require(:post).permit(:title, :body, :user_id, :env, tag_list: []) et c'était reglé

2021-12-11 19:30 UTC, phanremy commented
on est pas d'accord sur les tags, je m'occupe sur l'attribut `language` d'abord sur lequel on est ok

2022-01-12 22:23 UTC, b0rdjack commented
@phanremy Du coup on peut fermer cette PR suite au merge de la #40 ?

2022-04-10 09:33 UTC, closed without merging