Feature - language
CheatCheet/cheatcheet pull request #50
Opened 2021-12-11 21:15 UTC by phanremy

2021-12-12 22:20 UTC, b0rdjack requested changes

2021-12-12 22:20 UTC, b0rdjack commented on app/views/posts/_form.html.erb
> +      <%= f.text_field :title, style: 'width: 100%' %>
Il est préférable d'ajouter le style dans une feuille de style plutôt que dans le HTML.

2021-12-12 22:20 UTC, b0rdjack commented on app/views/posts/_form.html.erb
> +      <%= f.text_area :body, style: 'width: 100%' %>
Même remarque, le style dans un fichier `.scss`

2021-12-12 22:20 UTC, b0rdjack commented on app/models/language.rb
> +end
Pourquoi pas ajouter une validation au niveau du `name` pour le rendre unique ?

2021-12-12 22:20 UTC, b0rdjack commented on app/helpers/posts_helper.rb
> +    options_for_select(options, selected)
On peut simplifier avec `options_for_select(options, post_language_id)`

2021-12-12 22:20 UTC, b0rdjack commented on app/views/posts/_form.html.erb
> +      <%= f.select :language_id, language_collection(post.language_id), {}, { data: { 'controller': 'slim-select' } } %>
Pourquoi pas, mais on pourrait aussi utiliser [collection_select ](https://apidock.com/rails/ActionView/Helpers/FormOptionsHelper/collection_select) non ? Je ne sais pas lequel est le mieux 🤔

2021-12-12 22:29 UTC, b0rdjack commented
@phanremy Je viens de me rendre que le terme _Language_ n'est peut-être pas le plus adapté. Un exemple tout simple est _RubyOnRails_, qui n'est pas un langage mais _framework_. On pourrait utiliser _Technology_ peut-être ? De cette manière ça correspondra aux langages de programmation mais aussi aux _frameworks_

2021-12-12 23:27 UTC, phanremy commented on app/views/posts/_form.html.erb
> +      <%= f.text_field :title, style: 'width: 100%' %>
crée classe 'w-100', apres j'imagine que simplecss prefererai que l'on travaille sur les balises HTML

2021-12-12 23:29 UTC, phanremy commented
du coup je pense que je prefere `Environment` au lieu de `Technology` mais ca se vaut

2021-12-12 23:34 UTC, phanremy commented on app/views/posts/_form.html.erb
> +      <%= f.select :language_id, language_collection(post.language_id), {}, { data: { 'controller': 'slim-select' } } %>
Je préfère ma méthode à deux parametres que collection_select utilisant 6! xD mais c'est bon a connaitre

2021-12-17 22:16 UTC, phanremy commented on app/views/posts/_form.html.erb
> +      <%= f.text_area :body, style: 'width: 100%' %>
class 'w-100' crée

2021-12-17 22:16 UTC, phanremy commented
parti sur `Stack` au final

2022-01-03 22:45 UTC, b0rdjack commented
@phanremy Conflits à corriger 😅

2022-01-05 00:49 UTC, phanremy commented
c'est fait! par contre si tu veux bien tester la branche, j'ai l'impression que simplecss ne marche pas dessus

2022-01-12 15:13 UTC, b0rdjack commented on db/migrate/20211211194450_add_stack_to_posts.rb
> +    add_reference :posts, :stack, foreign_key: true
On peut mettre ça dans la migration `CreateStacks` pour tout avoir à un endroit.

2022-01-12 15:17 UTC, b0rdjack commented on test/fixtures/posts.yml
>    updated_at: 'Fri, 03 Dec 2021 23:32:25.947965000 UTC +00:00'
On peut supprimer ces lignes.

2022-01-12 15:18 UTC, b0rdjack commented on test/fixtures/posts.yml
>    updated_at: 'Fri, 03 Dec 2021 23:32:25.947965000 UTC +00:00'
On peut supprimer ces lignes.

2022-01-12 15:19 UTC, b0rdjack commented on test/controllers/posts_controller_test.rb
Il faut aussi ajouter la vérification que la relation avec la `Stack` est nul lorsqu'on supprimer un `Post`.

2022-01-12 15:21 UTC, b0rdjack requested changes

2022-01-12 15:21 UTC, b0rdjack commented on app/helpers/posts_helper.rb
> +  def stack_collection(post_stack_id)
```suggestion
  def stack_collection(stack_id)
```

2022-01-12 16:33 UTC, b0rdjack commented
@phanremy Il faudrait aussi supprimer les `tags`

2022-01-12 21:12 UTC, phanremy commented on db/seeds.rb
> +warn '==> End of stacks finding or creation'
pourquoi pas, à la fois pour la production et developpement

2022-01-12 21:33 UTC, merged